name: Daily Script

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-daily:
    
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.9


      - name: Install dependencies
        run: |
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install requests
      
      - name: Run my script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: |
          python3.9 alerts/sms.py
