name: Daily Script

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # or any other version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          # Add any other libraries your script needs here, like simplejson
          curl -u "${{ secrets.BASIC_AUTH_USERNAME }}:${{ secrets.BASIC_AUTH_PASSWORD }}" "https://api.x-eh.com/extapi3/"
          
      - name: Run my script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          API_REFRESH_TOKEN: ${{ secrets.API_REFRESH_TOKEN }}
        run: |
          python alerts/sms.py
