name: Daily Script

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight UTC
  workflow_dispatch:

jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run my script
        env:   # expose secrets to the script as environment variables
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
        run: |
          python alerts/sms.py
